---
- name: Download phantomjs
  unarchive:
    src: "https://github.com/Medium/phantomjs/releases/download/v{{ phantomjs_version }}/phantomjs-{{ phantomjs_version }}-linux-x86_64.tar.bz2"
    dest: "{{ workspace }}"
    copy: no
    creates: "{{ workspace }}/phantomjs-{{ phantomjs_version }}-linux-x86_64.tar.bz2"

- name: Add phantomjs to local bin.
  copy:
    src: "{{ workspace }}/phantomjs-2.1.1-linux-x86_64/bin/phantomjs"
    dest: "{{ phantomjs_bin_path }}"
    mode: 0755
